const PERMISSIONS = {
    // User
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",

    // Client
    CLIENT_CREATE: "CLIENT_CREATE",
    CLIENT_UPDATE: "CLIENT_UPDATE",
    CLIENT_DELETE: "CLIENT_DELETE",

    // Vendor
    VENDOR_CREATE: "VENDOR_CREATE",
    VENDOR_UPDATE: "VENDOR_UPDATE",
    VENDOR_DELETE: "VENDOR_DELETE",

    // Driver
    DRIVER_CREATE: "DRIVER_CREATE",
    DRIVER_UPDATE: "DRIVER_UPDATE",
    DRIVER_DELETE: "DRIVER_DELETE",
    DRIVER_ASSIGN: "DRIVER_ASSIGN",

    // Vehicle
    VEHICLE_CREATE: "VEHICLE_CREATE",
    VEHICLE_UPDATE: "VEHICLE_UPDATE",
    VEHICLE_DELETE: "VEHICLE_DELETE",

    // Event
    EVENT_CREATE: "EVENT_CREATE",
    EVENT_UPDATE: "EVENT_UPDATE",
    EVENT_DELETE: "EVENT_DELETE",

    // Guest
    GUEST_CREATE: "GUEST_CREATE",
    GUEST_UPDATE: "GUEST_UPDATE",
    GUEST_DELETE: "GUEST_DELETE",
    GUEST_ASSIGN: "GUEST_ASSIGN",

    // Billing
    BILL_GENERATE: "BILL_GENERATE",
    BILL_APPROVE: "BILL_APPROVE",
    BILL_SHARE: "BILL_SHARE",
    BILL_MARK_PAID: "BILL_MARK_PAID",

    // Invoice
    INVOICE_APPROVE: "INVOICE_APPROVE",
    INVOICE_PUBLISH: "INVOICE_PUBLISH",

    // Settlement
    SETTLEMENT_APPROVE: "SETTLEMENT_APPROVE",
};

module.exports = PERMISSIONS;