const PERMISSIONS = {
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  EVENT_CREATE: "EVENT_CREATE",
  EVENT_UPDATE: "EVENT_UPDATE",
  EVENT_DELETE: "EVENT_DELETE",

  GUEST_CREATE: "GUEST_CREATE",
  GUEST_ASSIGN: "GUEST_ASSIGN",

  DRIVER_ASSIGN: "DRIVER_ASSIGN",

  INVOICE_APPROVE: "INVOICE_APPROVE",
  INVOICE_PUBLISH: "INVOICE_PUBLISH",

  SETTLEMENT_APPROVE: "SETTLEMENT_APPROVE",
};

module.exports = PERMISSIONS;