const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",

    ADMIN: "ADMIN",

    OPERATIONS_MANAGER: "OPERATIONS_MANAGER",

    DISPATCHER: "DISPATCHER",

    ACCOUNTS: "ACCOUNTS",

    CLIENT: "CLIENT",

    VENDOR: "VENDOR",

    DRIVER: "DRIVER",

    SUPPORT: "SUPPORT",
};

module.exports = ROLES;