const STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED",
    BLOCKED: "BLOCKED",
};

const GUEST_STATUS = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
};

const VEHICLE_STATUS = {
    AVAILABLE: "AVAILABLE",
    ASSIGNED: "ASSIGNED",
    ON_DUTY: "ON_DUTY",
    MAINTENANCE: "MAINTENANCE",
    INACTIVE: "INACTIVE",
};

const EVENT_STATUS = {
    UPCOMING: "UPCOMING",
    ONGOING: "ONGOING",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
};

const BILL_STATUS = {
    DRAFT: "DRAFT",
    UNDER_REVIEW: "UNDER_REVIEW",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    SHARED: "SHARED",
    PAID: "PAID",
};

const TRIP_STAGE = {
    NOT_STARTED: "NOT_STARTED",
    PICKUP_STARTED: "PICKUP_STARTED",
    PICKUP_COMPLETED: "PICKUP_COMPLETED",
    EVENT_DUTY: "EVENT_DUTY",
    RETURN_STARTED: "RETURN_STARTED",
    RETURN_COMPLETED: "RETURN_COMPLETED",
    COMPLETED: "COMPLETED",
};

const NOTIFICATION_TYPE = {
    DRIVER_ASSIGNED: "DRIVER_ASSIGNED",

    PICKUP_STARTED: "PICKUP_STARTED",
    PICKUP_COMPLETED: "PICKUP_COMPLETED",

    RETURN_STARTED: "RETURN_STARTED",
    RETURN_COMPLETED: "RETURN_COMPLETED",

    DUTY_COMPLETED: "DUTY_COMPLETED",

    VENDOR_BILL_DRAFT: "VENDOR_BILL_DRAFT",
    VENDOR_BILL_APPROVED: "VENDOR_BILL_APPROVED",
    VENDOR_BILL_REJECTED: "VENDOR_BILL_REJECTED",

    CLIENT_INVOICE_DRAFT: "CLIENT_INVOICE_DRAFT",
    CLIENT_INVOICE_APPROVED: "CLIENT_INVOICE_APPROVED",
    CLIENT_INVOICE_REJECTED: "CLIENT_INVOICE_REJECTED",

    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
};

const PICKUP_STATUS = {
    PENDING: "PENDING",
    DRIVER_EN_ROUTE: "DRIVER_EN_ROUTE",
    PICKED_UP: "PICKED_UP",
    DROPPED_AT_VENUE: "DROPPED_AT_VENUE",
};

const RETURN_STATUS = {
    NOT_STARTED: "NOT_STARTED",
    RETURN_PICKUP: "RETURN_PICKUP",
    DROPPED: "DROPPED",
};

const VEHICLE_ASSIGNMENT_STATUS = {
    ASSIGNED: "ASSIGNED",
    ON_DUTY: "ON_DUTY",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
};

const DUTY_STATUS = {
    STARTED: "STARTED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
};
module.exports = {
    STATUS,
    EVENT_STATUS,
    BILL_STATUS,
    TRIP_STAGE,
    NOTIFICATION_TYPE,
    GUEST_STATUS,
    VEHICLE_STATUS,
    PICKUP_STATUS,
    RETURN_STATUS,
    DUTY_STATUS,
    VEHICLE_ASSIGNMENT_STATUS,
};