const STATUS = {
  ACTIVE: "ACTIVE",

  INACTIVE: "INACTIVE",

  SUSPENDED: "SUSPENDED",

  BLOCKED: "BLOCKED",
};

const EVENT_STATUS = {

    UPCOMING: "UPCOMING",

    ONGOING: "ONGOING",

    COMPLETED: "COMPLETED",

    CANCELLED: "CANCELLED",

};

const BILL_STATUS = {

    DRAFT: "DRAFT",

    UNDER_REVIEW: "UNDER_REVIEW",

    APPROVED: "APPROVED",

    REJECTED: "REJECTED",

    SHARED: "SHARED",

    PAID: "PAID",

};

const TRIP_STAGE = {

    PICKUP_STARTED: "PICKUP_STARTED",

    PICKUP_COMPLETED: "PICKUP_COMPLETED",

    EVENT_DUTY: "EVENT_DUTY",

    RETURN_STARTED: "RETURN_STARTED",

    RETURN_COMPLETED: "RETURN_COMPLETED",

};


const NOTIFICATION_TYPE = {

    DRIVER_ASSIGNED: "DRIVER_ASSIGNED",

    PICKUP_STARTED: "PICKUP_STARTED",

    PICKUP_COMPLETED: "PICKUP_COMPLETED",

    RETURN_STARTED: "RETURN_STARTED",

    RETURN_COMPLETED: "RETURN_COMPLETED",

    DUTY_COMPLETED: "DUTY_COMPLETED",

    VENDOR_BILL_DRAFT: "VENDOR_BILL_DRAFT",

    VENDOR_BILL_APPROVED: "VENDOR_BILL_APPROVED",

    CLIENT_INVOICE_DRAFT: "CLIENT_INVOICE_DRAFT",

    CLIENT_INVOICE_APPROVED: "CLIENT_INVOICE_APPROVED",

    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",

};

module.exports = {

    EVENT_STATUS,

    BILL_STATUS,
    TRIP_STAGE,
    STATUS,
    NOTIFICATION_TYPE,

};
